import { defineConfig } from 'tsup';

export default defineConfig([
  // Main build for Node.js environment with tree-shaking support
  {
    entry: {
      index: 'src/index.ts',
      instrumentation: 'src/instrumentation.ts',
      logger: 'src/logger.ts',
      'logger-winston': 'src/logger-winston.ts',
      'trace-helpers': 'src/trace-helpers.ts',
      sampling: 'src/sampling.ts',
      analytics: 'src/analytics.ts',
      'analytics-adapter': 'src/analytics-adapter.ts',
      'analytics-testing': 'src/analytics-testing.ts',
      metrics: 'src/metrics.ts',
      'metrics-testing': 'src/metrics-testing.ts',
      testing: 'src/testing.ts',
      config: 'src/config.ts',
      'tail-sampling-processor': 'src/tail-sampling-processor.ts',
      functional: 'src/functional.ts',
      http: 'src/http.ts',
      db: 'src/db.ts',
      decorators: 'src/decorators.ts',
    },
    format: ['esm'], // ESM only for better tree-shaking
    dts: true,
    sourcemap: true,
    outDir: 'dist',
    clean: true,
    treeshake: true, // Enable aggressive tree-shaking
    splitting: true, // Enable code splitting for shared chunks
    minify: false, // Let bundlers handle minification
    // Mark logger implementations as external so user bundlers can tree-shake
    external: ['pino', 'pino-pretty', 'winston'],
  },
  // Legacy CJS build for backwards compatibility
  {
    entry: ['src/index.ts'],
    format: ['cjs'],
    dts: false, // Types already generated by ESM build
    sourcemap: true,
    outDir: 'dist',
    clean: false,
  },
]);
