import { defineConfig } from 'tsup';

export default defineConfig([
  // Main build for Node.js environment with tree-shaking support
  {
    entry: {
      index: 'src/index.ts',
      instrumentation: 'src/instrumentation.ts',
      logger: 'src/logger.ts',
      'trace-helpers': 'src/trace-helpers.ts',
      'tracer-provider': 'src/tracer-provider.ts',
      'semantic-helpers': 'src/semantic-helpers.ts',
      sampling: 'src/sampling.ts',
      event: 'src/event.ts',
      'event-subscriber': 'src/event-subscriber.ts',
      'event-testing': 'src/event-testing.ts',
      metric: 'src/metric.ts',
      'metric-testing': 'src/metric-testing.ts',
      'metric-helpers': 'src/metric-helpers.ts',
      testing: 'src/testing.ts',
      exporters: 'src/exporters.ts',
      processors: 'src/processors.ts',
      config: 'src/config.ts',
      'tail-sampling-processor': 'src/tail-sampling-processor.ts',
      functional: 'src/functional.ts',
      http: 'src/http.ts',
      db: 'src/db.ts',
      decorators: 'src/decorators.ts',
      'presets/datadog': 'src/presets/datadog.ts',
      'presets/honeycomb': 'src/presets/honeycomb.ts',
    },
    format: ['esm'], // ESM only for better tree-shaking
    dts: true,
    sourcemap: true,
    outDir: 'dist',
    clean: true,
    treeshake: true, // Enable aggressive tree-shaking
    splitting: true, // Enable code splitting for shared chunks
    minify: false, // Let bundlers handle minification
    // Mark logger implementations as external so user bundlers can tree-shake
    external: ['pino', 'pino-pretty', 'winston'],
  },
  // Legacy CJS build for backwards compatibility
  {
    entry: ['src/index.ts'],
    format: ['cjs'],
    dts: false, // Types already generated by ESM build
    sourcemap: true,
    outDir: 'dist',
    clean: false,
  },
]);
